// GENERATED by scripts/generate-assets.ts — do not edit by hand.
// Regenerate with: npm run generate:assets

export interface AssetRow {
  symbol: string
  name: string
  token: `0x${string}`
  feed: `0x${string}`
  heartbeat: number
}

export const GENERATED_AT = '2026-09-09T11:55:20.449Z'
export const TOTAL_ASSETS = 194
export const COVERED_ASSETS = 35

export const ASSETS: AssetRow[] = [
  {
    "symbol": "AAPL",
    "name": "Apple",
    "token": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9",
    "feed": "0x6B22A786bAa607d76728168703a39Ea9C99f2cD0",
    "heartbeat": 86400
  },
  {
    "symbol": "AMD",
    "name": "AMD",
    "token": "0x86923f96303D656E4aa86D9d42D1e57ad2023fdC",
    "feed": "0x943A29E7ae51A4798823ca9eEd2ed533B2A22C72",
    "heartbeat": 86400
  },
  {
    "symbol": "AMZN",
    "name": "Amazon",
    "token": "0x12f190a9F9d7D37a250758b26824B97CE941bF54",
    "feed": "0xD5a1508ceD74c084eBf3cBe853e2C968fB2a651C",
    "heartbeat": 86400
  },
  {
    "symbol": "ASML",
    "name": "ASML Holding NV",
    "token": "0x47F93d52cBeC7C6D2CfC080e154002370a60dAEA",
    "feed": "0xB4106147E8cce40b7d46124090d373A71b70f87D",
    "heartbeat": 86400
  },
  {
    "symbol": "BABA",
    "name": "Alibaba",
    "token": "0xad25Ac6C84D497db898fa1E8387bf6Af3532a1c4",
    "feed": "0x62Cc8F9b5f56a33c9C8A60c8B92779f523c4E984",
    "heartbeat": 86400
  },
  {
    "symbol": "CLSK",
    "name": "CleanSpark",
    "token": "0xcBB95BBF36099d34dA091dc6Fa6F49EfA257Cee3",
    "feed": "0x810c12D3a554Bc47fd39597Fe3b3AAC4941F50eF",
    "heartbeat": 86400
  },
  {
    "symbol": "COIN",
    "name": "Coinbase",
    "token": "0x6330D8C3178a418788dF01a47479c0ce7CCF450b",
    "feed": "0xA3a468A452940B7D6b69991207B508c609a98Ef2",
    "heartbeat": 86400
  },
  {
    "symbol": "CRCL",
    "name": "Circle Internet Group",
    "token": "0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5",
    "feed": "0x6652eDf64bA3731C4F2D3ce821A0Fb1f1f6b482a",
    "heartbeat": 86400
  },
  {
    "symbol": "CRWV",
    "name": "CoreWeave",
    "token": "0x5f10A1C971B69e47e059e1dC91901B59b3fB49C3",
    "feed": "0xe1b3aABCAFAd1c94708dc1367dcfF8Aa4407487C",
    "heartbeat": 86400
  },
  {
    "symbol": "DELL",
    "name": "Dell",
    "token": "0x941AE714EC6D8130c7B75d67160Ca08f1e7d11Dd",
    "feed": "0x1C6c8cADBe02E19129c39dDB92281cE4c0bf206b",
    "heartbeat": 86400
  },
  {
    "symbol": "EWY",
    "name": "iShares MSCI South Korea fund",
    "token": "0x7f0aBeF0C07280F82c6a08ead09dEd6BAE2C13Fc",
    "feed": "0xEFdf54610B62A7753Ec30bDc380847c12D32e1D1",
    "heartbeat": 86400
  },
  {
    "symbol": "GME",
    "name": "GameStop",
    "token": "0x1b0E319c6A659F002271B69dB8A7df2F911c153E",
    "feed": "0x27C71df6A64fB476468EdF256CF72c038baB5B67",
    "heartbeat": 86400
  },
  {
    "symbol": "GOOGL",
    "name": "Alphabet Class A",
    "token": "0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3",
    "feed": "0xF6f373a037c30F0e5010d854385cA89185AE638b",
    "heartbeat": 86400
  },
  {
    "symbol": "INTC",
    "name": "Intel",
    "token": "0xc72b96e0E48ecd4DC75E1e45396e26300BC39681",
    "feed": "0x3f390C5C24628Ac7C489515402235FeAD71D1913",
    "heartbeat": 86400
  },
  {
    "symbol": "IONQ",
    "name": "IonQ",
    "token": "0x558378E000D634A36593E338eBacdd6207640EfE",
    "feed": "0x22EfeC4919baf55F360E0EDee4AbEB26DE4971eb",
    "heartbeat": 86400
  },
  {
    "symbol": "META",
    "name": "Meta Platforms",
    "token": "0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35",
    "feed": "0x7C38C00C30BEe9378381E7B6135d7283356D71b1",
    "heartbeat": 86400
  },
  {
    "symbol": "MSFT",
    "name": "Microsoft",
    "token": "0xe93237C50D904957Cf27E7B1133b510C669c2e74",
    "feed": "0x45C3C877C15E6BA2EBB19eA114Ea508d14C1Af2E",
    "heartbeat": 86400
  },
  {
    "symbol": "MSTR",
    "name": "Strategy Inc.",
    "token": "0xec262a75e413fAfD0dF80480274532C79D42da09",
    "feed": "0x396118bdFB181e6240E74D243F266B061c0edc3D",
    "heartbeat": 86400
  },
  {
    "symbol": "MU",
    "name": "Micron Technology",
    "token": "0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD",
    "feed": "0x425EEFdCf05ed6526C3cE61Af99429A228a6d596",
    "heartbeat": 86400
  },
  {
    "symbol": "NBIS",
    "name": "Nebius Group",
    "token": "0x9D9c6684F596F66a64C030B93A886D51Fd4D7931",
    "feed": "0xE1D87B116Ba0fe898998f1D140339D1fA1E09705",
    "heartbeat": 86400
  },
  {
    "symbol": "NVDA",
    "name": "NVIDIA",
    "token": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
    "feed": "0x379EC4f7C378F34a1B47E4F3cbeBCbAC3E8E9F15",
    "heartbeat": 86400
  },
  {
    "symbol": "ORCL",
    "name": "Oracle",
    "token": "0xb0992820E760d836549ba69BC7598b4af75dEE03",
    "feed": "0x0e6a64a2B58A6693a531E6c555f3A5d042eEA844",
    "heartbeat": 86400
  },
  {
    "symbol": "PLTR",
    "name": "Palantir Technologies",
    "token": "0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A",
    "feed": "0x820ABedFF239034956B7A9d2F0a331f9F075eB4c",
    "heartbeat": 86400
  },
  {
    "symbol": "QQQ",
    "name": "Invesco QQQ",
    "token": "0xD5f3879160bc7c32ebb4dC785F8a4F505888de68",
    "feed": "0x80901d846d5D7B030F26B480776EE3b29374C2ae",
    "heartbeat": 86400
  },
  {
    "symbol": "RGTI",
    "name": "Rigetti Computing",
    "token": "0x284358abc07F9359f19f4b5b4aC91901Be2597Ba",
    "feed": "0x2A045cF1C49c61c166C036d2f06FA2D2d984f765",
    "heartbeat": 86400
  },
  {
    "symbol": "RKLB",
    "name": "Rocket Lab Corporation",
    "token": "0x3b14C39E89D60D627b42a1A4CA45b5bb45Fc12e2",
    "feed": "0x045477BF65Aef6f4F2386ad0164579e48381CC74",
    "heartbeat": 86400
  },
  {
    "symbol": "SGOV",
    "name": "iShares 0-3 Month Treasury Bond",
    "token": "0x92FD66527192E3e61d4DDd13322Aa222DE86F9B5",
    "feed": "0xa0DF4ee0fFf975306345875E3548Fcc519577A11",
    "heartbeat": 86400
  },
  {
    "symbol": "SLV",
    "name": "iShares Silver Trust",
    "token": "0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f",
    "feed": "0x209b73908e92Ae021826eD79609845451Ecba2ce",
    "heartbeat": 86400
  },
  {
    "symbol": "SNDK",
    "name": "Sandisk Corporation",
    "token": "0xB90A19fF0Af67f7779afF50A882A9CfF42446400",
    "feed": "0xfb133Fa4B7b385802B693a293606682Df47109A3",
    "heartbeat": 86400
  },
  {
    "symbol": "SPCX",
    "name": "Space Exploration Technologies Corp. Class A Common Stock",
    "token": "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa",
    "feed": "0xB265810950ba6c5C0Ff821c9963014a56fD8Bffb",
    "heartbeat": 86400
  },
  {
    "symbol": "SPY",
    "name": "SPDR S&P 500 ETF Trust",
    "token": "0x117cc2133c37B721F49dE2A7a74833232B3B4C0C",
    "feed": "0x319724394D3A0e3669269846abE664Cd621f9f6A",
    "heartbeat": 86400
  },
  {
    "symbol": "TSLA",
    "name": "Tesla",
    "token": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d",
    "feed": "0x4A1166a659A55625345e9515b32adECea5547C38",
    "heartbeat": 86400
  },
  {
    "symbol": "TSM",
    "name": "Taiwan Semiconductor Manufacturing",
    "token": "0x58FfE4a942d3885bAa22D7520691F611EF09e7AA",
    "feed": "0x874cF94aa8eC88Fd9560094dD065f2fB3E41Fc2F",
    "heartbeat": 86400
  },
  {
    "symbol": "USAR",
    "name": "USA Rare Earth",
    "token": "0xd917B029C761D264c6A312BBbcDA868658eF86a6",
    "feed": "0xA994d3684e8400A6c8078226925779FdeE682DD9",
    "heartbeat": 86400
  },
  {
    "symbol": "USO",
    "name": "United States Oil Fund",
    "token": "0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344",
    "feed": "0x75a9c76Ef439e2C7c2E5a34Ab105EcFe3766431c",
    "heartbeat": 86400
  }
] as AssetRow[]
