import { writeFileSync } from 'node:fs'

const ASSETS_URL = 'https://api.robinhood.com/rhj/assets'
const FEEDS_URL = 'https://reference-data-directory.vercel.app/feeds-robinhood-mainnet.json'
const CHAIN_ID = 4663

interface RegistryAsset {
  tokenSymbol: string
  tokenName: string
  deployments: { contractAddress: string; chainId: number }[]
  currentMultiplier: string
}

interface FeedEntry {
  name?: string
  assetName?: string
  proxyAddress: string
  heartbeat: number
  docs?: { baseAsset?: string }
}

async function main() {
  const [assetsRes, feedsRes] = await Promise.all([fetch(ASSETS_URL), fetch(FEEDS_URL)])
  if (!assetsRes.ok) throw new Error(`assets: HTTP ${assetsRes.status}`)
  if (!feedsRes.ok) throw new Error(`feeds: HTTP ${feedsRes.status}`)

  const assets: RegistryAsset[] = ((await assetsRes.json()) as { assets: RegistryAsset[] }).assets
  const feeds = (await feedsRes.json()) as FeedEntry[]

  // Only feeds that track a Robinhood tokenized asset.
  const rhFeeds = feeds.filter(
    (f) => /robinhood/i.test(f.name ?? '') || /Robinhood/i.test(f.assetName ?? ''),
  )

  const feedBySymbol = new Map<string, FeedEntry>()
  for (const f of rhFeeds) {
    let sym = f.docs?.baseAsset ?? null
    if (!sym) sym = /Robinhood ([A-Z]+)-USD/.exec(f.name ?? '')?.[1] ?? null
    // The DELL feed is published under the RHDELL base asset.
    if (sym === 'RHDELL') sym = 'DELL'
    if (sym) feedBySymbol.set(sym, f)
  }

  const rows = assets
    .map((a) => {
      const deployment = a.deployments.find((d) => d.chainId === CHAIN_ID)
      const feed = feedBySymbol.get(a.tokenSymbol)
      if (!deployment || !feed) return null
      return {
        symbol: a.tokenSymbol,
        name: a.tokenName.replace(' • Robinhood Token', ''),
        token: deployment.contractAddress,
        feed: feed.proxyAddress,
        heartbeat: feed.heartbeat,
      }
    })
    .filter((r): r is NonNullable<typeof r> => r !== null)
    .sort((a, b) => a.symbol.localeCompare(b.symbol))

  if (rows.length === 0) throw new Error('no assets resolved — refusing to write an empty registry')

  const body = `// GENERATED by scripts/generate-assets.ts — do not edit by hand.
// Regenerate with: npm run generate:assets

export interface AssetRow {
  symbol: string
  name: string
  token: \`0x\${string}\`
  feed: \`0x\${string}\`
  heartbeat: number
}

export const GENERATED_AT = '${new Date().toISOString()}'
export const TOTAL_ASSETS = ${assets.length}
export const COVERED_ASSETS = ${rows.length}

export const ASSETS: AssetRow[] = ${JSON.stringify(rows, null, 2)} as AssetRow[]
`

  writeFileSync('lib/assets.generated.ts', body)
  console.log(`wrote ${rows.length} covered assets of ${assets.length} total`)
}

main()
